const noop = (...args: any[]) => ({ mutateAsync: async (...args: any[]) => {}, mutate: (...args: any[]) => {}, isPending: false, isSuccess: false });
const queryMock = (...args: any[]) => ({ data: null, isLoading: false, isSuccess: false });

export const useLogin = noop;
export const useRegister = noop;
export const useGetMe = queryMock;
export const useGetProjectStats = queryMock;
export const useListProjects = queryMock;
export const useCreateProject = noop;
export const useDeleteProject = noop;
export const getListProjectsQueryKey = () => [];
export const useGetDocumentation = queryMock;
export const useUpdateDocumentation = noop;
export const getGetDocumentationQueryKey = () => [];
export const useGetReadiness = queryMock;
export const useGetEligibility = queryMock;
export const useSubmitEligibility = noop;
export const useGetProject = queryMock;
export const useListReviews = queryMock;
export const useCreateReview = noop;
export const getListReviewsQueryKey = () => [];
export const useExportDocument = noop;
export const useListGaps = queryMock;
export const useUpdateGap = noop;
export const getListGapsQueryKey = () => [];
export const useGetKnowledgeBase = queryMock;
export const useUpdateKnowledgeBase = noop;
export const useListDocuments = queryMock;
export const useUploadDocument = noop;
export const useProcessDocument = noop;
export const getListDocumentsQueryKey = () => [];
export const useListValidations = queryMock;
export const useRunValidation = noop;
export const getListValidationsQueryKey = () => [];

export const RegisterInputRole: any = {}; export type RegisterInputRole = any;
export const Project: any = {}; export type Project = any;
export const DocSection: any = {}; export type DocSection = any;
export const ReadinessDashboard: any = {}; export type ReadinessDashboard = any;
export const Review: any = {}; export type Review = any;
export const ReviewInputAction: any = {}; export type ReviewInputAction = any;
export const ExportInputFormat: any = {}; export type ExportInputFormat = any;
export const ComplianceGap: any = {}; export type ComplianceGap = any;
export const GapUpdateStatus: any = {}; export type GapUpdateStatus = any;
export const DocumentInputFileType: any = {}; export type DocumentInputFileType = any;
export const ValidationIssue: any = {}; export type ValidationIssue = any;
