import { ActivitySquare, FileText, Layers, ShieldCheck } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

interface Feature {
  icon: LucideIcon
  title: string
  body: string
}

// Copy trimmed from the original to describe what this app actually does —
// the source deck promised a "live preview" and "readiness scores" that
// don't exist here, and overclaiming to a SEBI audience is worse than
// saying less. Each line below maps to a real built capability.
const FEATURES: Feature[] = [
  {
    icon: Layers,
    title: 'Structured knowledge base',
    body: 'Company data, financials, capital structure, promoters and litigation land in one typed fact model instead of scattered across documents.',
  },
  {
    icon: FileText,
    title: 'Sourced document assembly',
    body: 'Every assembled section is built from confirmed facts, and every figure carries a citation back to the page it came from.',
  },
  {
    icon: ShieldCheck,
    title: 'Deterministic eligibility checks',
    body: 'Six SEBI-oriented rules run on the extracted data — never generated by a model — each reporting whether it is backed by confirmed or unconfirmed values.',
  },
  {
    icon: ActivitySquare,
    title: 'Immutable audit trail',
    body: 'Extraction, edits, confirmations and conflict resolutions are all appended to a write-once event log. Nothing changes without a record.',
  },
]

export function LandingFeatures() {
  return (
    <section id="features" className="scroll-mt-16 border-b border-hairline bg-paper-raised px-6 py-24">
      <div className="mx-auto max-w-5xl">
        <div className="mx-auto max-w-2xl text-center">
          <p className="text-sm font-semibold tracking-wide text-confirmed uppercase">Everything you need</p>
          <h2 className="mt-3 text-3xl text-balance text-ink sm:text-4xl">Command centre for IPO readiness</h2>
          <p className="mt-6 text-lg leading-8 text-pretty text-ink-muted">
            A purpose-built platform that handles the complexity of regulatory compliance while keeping a
            human in control of every fact that reaches the filing.
          </p>
        </div>

        <dl className="mx-auto mt-16 grid max-w-4xl grid-cols-1 gap-6 lg:grid-cols-2">
          {FEATURES.map(({ icon: Icon, title, body }) => (
            <div key={title} className="interactive rounded-lg border border-hairline bg-paper p-6">
              <dt className="flex items-center gap-3 text-base font-semibold text-ink">
                <span className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-confirmed-tint text-confirmed">
                  <Icon className="size-5" />
                </span>
                {title}
              </dt>
              <dd className="mt-3 text-sm leading-6 text-ink-muted">{body}</dd>
            </div>
          ))}
        </dl>
      </div>
    </section>
  )
}
